version: 0.2
env:
  secrets-manager:
    APISECRETKEY: mysecret:aoraky
phases:
  install:
    commands:
      - echo $APISECRETKEY
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - echo secretvalue is $APISECRETKEY
      
artifacts:
  files:
    - '**/*'
