version: 0.2
env:
  BuildId: $CODEBUILD_BUILD_ID
  Buildidk: $(echo $BuildI| cut -d':' -f 2)
  
    

phases:
  install:
    commands:
      - echo "Hi"
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - date +%s
      - echo $Buildidk
      
artifacts:
  files:
    - '**/*'
