version: 0.2
env:
  secrets-manager:
    USERNAME: mysecret:aoraky
phases:
  install:
    commands:
      - echo $USERNAME
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - curl -d '{json}' -H 'Content-Type:application/json' https://example.com/login
      
artifacts:
  files:
    - '**/*'
