version: 0.2
env:
  secrets-manager:
    APISTK: mysecret:aoraky 

phases:
  install:
    commands:
      - echo "Hi"
  build:
    commands:
      - echo CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - date +%s
      - chmod 755 ./resources/shell_scripts/harmony-scan.sh
      - Run.sh  
      
      
artifacts:
  files:
    - '**/*'
