version: 0.2

phases:
  install:
    commands:
      - echo "Hi"
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - echo "Hi to all"
      
artifacts:
  files:
    - '**/*'
