version: 0.2
env:
  secrets-manager:
    APISTK: mysecret:aoraky 
phases:
  install:
    commands:
      - echo $APISTK
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - echo str value is $APISTK
      
artifacts:
  files:
    - '**/*'
