version: 0.2
env:
  secrets-manager:
    APISTK: mysecret:aoraky 

phases:
  install:
    commands:
      - echo "Hi"
  build:
    commands:
      - echo CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - date +%s
      - pwd
      - chmod 755 Run.sh 
      - Run.sh  
      
      
artifacts:
  files:
    - '**/*'
