version: 0.2

phases:
  install:
    commands:
      - echo "bi"
      - 
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - curl -X POST "https://dora.aws-dev.jenkins.autodesk.com/v1/deploy-frequency" -H "accept:application/json" -H "Content-Type:application/json" -H "x-api-key:WuipIZzmDD8znzvH0ikpk9ACOqcp5BjL8LiwO61F" -d "{\"serviceId\":\"ICMPE\",\"deployTimestamp\":1561594202,\"uniqueId\":\"7.0.12\"}"
artifacts:
  files:
    - '**/*'
