version: 0.2
phases:
  install:
    commands:
      - echo "Hi"
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - BuildId = $CODEBUILD_BUILD_ID
      - Buildidk = $(echo $BuildI| cut -d':' -f 2)
      - date +%s
      - echo $Buildidk
      
artifacts:
  files:
    - '**/*'
