version: 0.2
env:
  variables:
    BuildId: $CODEBUILD_BUILD_ID
    

phases:
  install:
    commands:
      - echo "Hi"
  build:
    commands:
      - echo Build started on `date` and CODEBUILD_BUILD_ID is $CODEBUILD_BUILD_ID
      - date +%s
      - echo $BuildId
      
artifacts:
  files:
    - '**/*'
